/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicFeedbackRouteImport } from './routes/_public/feedback'
import { Route as PublicLinksRouteImport } from './routes/_public/links'
import { Route as PublicReservationRouteImport } from './routes/_public/reservation'
import { Route as PublicPostsIndexRouteImport } from './routes/_public/posts.index'
import { Route as PublicPostsSlugRouteImport } from './routes/_public/posts.$slug'
import { Route as PublicTagsIndexRouteImport } from './routes/_public/tags.index'
import { Route as PublicTagsSlugRouteImport } from './routes/_public/tags.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeedbackRoute = PublicFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => PublicRoute,
} as any).lazy(() =>
  import('./routes/_public/feedback.lazy').then((d) => d.Route),
)
const PublicLinksRoute = PublicLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReservationRoute = PublicReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => PublicRoute,
} as any).lazy(() =>
  import('./routes/_public/reservation.lazy').then((d) => d.Route),
)
const PublicPostsIndexRoute = PublicPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostsSlugRoute = PublicPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTagsIndexRoute = PublicTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTagsSlugRoute = PublicTagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/feedback': typeof PublicFeedbackRoute
  '/links': typeof PublicLinksRoute
  '/reservation': typeof PublicReservationRoute
  '/posts/$slug': typeof PublicPostsSlugRoute
  '/tags/$slug': typeof PublicTagsSlugRoute
  '/posts/': typeof PublicPostsIndexRoute
  '/tags/': typeof PublicTagsIndexRoute
}
export interface FileRoutesByTo {
  '/feedback': typeof PublicFeedbackRoute
  '/links': typeof PublicLinksRoute
  '/reservation': typeof PublicReservationRoute
  '/': typeof PublicIndexRoute
  '/posts/$slug': typeof PublicPostsSlugRoute
  '/tags/$slug': typeof PublicTagsSlugRoute
  '/posts': typeof PublicPostsIndexRoute
  '/tags': typeof PublicTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/feedback': typeof PublicFeedbackRoute
  '/_public/links': typeof PublicLinksRoute
  '/_public/reservation': typeof PublicReservationRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/posts/$slug': typeof PublicPostsSlugRoute
  '/_public/tags/$slug': typeof PublicTagsSlugRoute
  '/_public/posts/': typeof PublicPostsIndexRoute
  '/_public/tags/': typeof PublicTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/links'
    | '/reservation'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/posts/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/feedback'
    | '/links'
    | '/reservation'
    | '/'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/posts'
    | '/tags'
  id:
    | '__root__'
    | '/_public'
    | '/_public/feedback'
    | '/_public/links'
    | '/_public/reservation'
    | '/_public/'
    | '/_public/posts/$slug'
    | '/_public/tags/$slug'
    | '/_public/posts/'
    | '/_public/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/feedback': {
      id: '/_public/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof PublicFeedbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/links': {
      id: '/_public/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof PublicLinksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reservation': {
      id: '/_public/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof PublicReservationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/posts/': {
      id: '/_public/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PublicPostsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/posts/$slug': {
      id: '/_public/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PublicPostsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tags/': {
      id: '/_public/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof PublicTagsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tags/$slug': {
      id: '/_public/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof PublicTagsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicFeedbackRoute: typeof PublicFeedbackRoute
  PublicLinksRoute: typeof PublicLinksRoute
  PublicReservationRoute: typeof PublicReservationRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPostsSlugRoute: typeof PublicPostsSlugRoute
  PublicTagsSlugRoute: typeof PublicTagsSlugRoute
  PublicPostsIndexRoute: typeof PublicPostsIndexRoute
  PublicTagsIndexRoute: typeof PublicTagsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFeedbackRoute: PublicFeedbackRoute,
  PublicLinksRoute: PublicLinksRoute,
  PublicReservationRoute: PublicReservationRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPostsSlugRoute: PublicPostsSlugRoute,
  PublicTagsSlugRoute: PublicTagsSlugRoute,
  PublicPostsIndexRoute: PublicPostsIndexRoute,
  PublicTagsIndexRoute: PublicTagsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
